server:
  port: 8888

#management.endpoints.web.exposure.include: health,info,refresh
spring:
  application:
    name: currency-spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/De-Saint/exchange_rate_microservices_config_server.git
          clone-on-start: true
          username: De-Saint
          password: old_testament

